server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    driverClassName: org.h2.Driver
    username: a
    password: password
  flyway:
    enabled: true
    locations: classpath:/db/migration

clients:
  users-api-host: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/users
  teams-api-host: https://cgjresszgg.execute-api.eu-west-1.amazonaws.com/teams
